auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("user", views.user, name="user"),
    path("categories", views.categories, name="categories"),
    path("create", views.create, name="create"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("listing/<int:listing_id>", views.listing, name="listing")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Bid(models.Model):
    listing = models.ForeignKey(
        'Listing',
        on_delete=models.CASCADE,
        related_name="bids"
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.PROTECT,
        verbose_name="Bidder",
        related_name="bids"
    )
    bid_amount = models.DecimalField(max_digits=8, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return(f"{self.user}: {self.bid_amount}")

class Category(models.Model):
    category = models.CharField(max_length=40)

    def __str__(self):
        return(self.category)

class Comment(models.Model):
    listing = models.ForeignKey(
        'Listing',
        on_delete=models.CASCADE,
        related_name="comments"
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.PROTECT,
        related_name="comments"
    )
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return(f"{self.user} on {self.listing}")

class Listing(models.Model):
    owner = models.ForeignKey(
        'User',
        on_delete=models.PROTECT,
        related_name="listings"
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    starting_bid = models.DecimalField(max_digits=8, decimal_places=2)
    image_URL = models.URLField(blank=True)
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="listings"
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return(f"{self.owner}: {self.title}")

class User(AbstractUser):
    pass

class Watchlist(models.Model):
    listing = models.ForeignKey(
        'Listing',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        'User',
        on_delete=models.PROTECT,
        related_name="watchlist"
    )

    def __str__(self):
        return(f"{self.user}: {self.listing}")

auctions/views.py
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.translation import gettext as _

from .models import User, Bid, Category, Comment, Listing, Watchlist
from .utils import get_bid


class CreateListing(forms.Form):
    title = forms.CharField(
        label='Title', 
        max_length=100, 
        help_text="100 characters max", 
        widget=forms.TextInput(attrs={"class":"form-control"})
        )
    description = forms.CharField(
        widget=forms.Textarea(attrs={"class":"form-control"})
        )
    starting_bid = forms.DecimalField(
        min_value=0.01, 
        max_digits=8, 
        decimal_places=2, 
        help_text="Provide the minimum starting bid", 
        widget=forms.NumberInput(attrs={"class":"form-control"})
        )
    image_URL = forms.URLField(
        label="Image URL", 
        required=False, 
        help_text="Provide a link to your image", 
        widget=forms.URLInput(attrs={"class":"form-control"})
        )

    # Generates tuple list of categories
    # Note: tuple required as choice field defines name and value
    options = Category.objects.all().order_by("category")
    categories = [(None, "Please select...")]
    for option in options:
        categories.append((option.id, option.category))
    
    category = forms.ChoiceField(
        choices=categories, 
        required=False,
        help_text="Select the most appropriate category for your listing",
        widget=forms.Select(attrs={"class":"form-control"})
        )
    owner = forms.IntegerField(
        widget=forms.HiddenInput
        )

class BidForm(forms.Form):
    current_bid = forms.DecimalField(
        widget=forms.HiddenInput
    )
    listing_id = forms.IntegerField(
        widget=forms.HiddenInput
    )
    user_id = forms.IntegerField(
        widget=forms.HiddenInput
    )
    bid_amount = forms.DecimalField(
        label="Place bid",
        max_digits=8,
        decimal_places=2
    )

    # Validates new bid is greater than current bid
    def clean_bid_amount(self):
        bid_amount = self.cleaned_data["bid_amount"]
        current_bid = self.cleaned_data["current_bid"]

        if bid_amount <= current_bid:
            error = ValidationError(
                _("Error: New bid must be greater than the previous bid of £%(bid)s"),
                code="invalid",
                params={"bid":current_bid})
            self.add_error("bid_amount", error)
        
        return bid_amount

    # Validation for current_bid owner vs current user
    ## TO DO

class CommentForm(forms.Form):
    listing_id = forms.IntegerField(
        label='',
        widget=forms.HiddenInput
    )
    user_id = forms.IntegerField(
        label='',
        widget=forms.HiddenInput
    )
    comment = forms.CharField(
        label="Add comment",
        widget=forms.Textarea(attrs={"class":"comments"})
    )

def index(request):

    # Gets all listings, POST method provides additional filters
    if request.method == "POST":
        category_id = request.POST['category']
        category = Category.objects.filter(id=category_id).get()
        listings = Listing.objects.filter(active=True, category_id=category_id).order_by('title')
    else:
        listings = Listing.objects.filter(active=True).order_by('title')
        category = None

    # Creates dict of highest bid for each listing
    bids = {}
    for listing in listings:
        bids.update(get_bid(listing))

    return render(request, "auctions/index.html", {
        "listings": listings,
        "bids": bids,
        "category": category
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            messages.error(request, "Invalid username and/or password", extra_tags="alert alert-danger")
            return render(request, "auctions/login.html")
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

def register(request):
    if request.method == "POST":

        # Ensure all fields provided
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        print(f"username = {username}, email = {email}, password = {password}, confirmation = {confirmation}")

        if username == '' or email == '' or password == '' or confirmation == '':
            print("None test")
            messages.error(request, "Error: Missing values", extra_tags="alert alert-danger")
            return render(request, "auctions/register.html")

        # Ensure password matches confirmation
        if password != confirmation:
            messages.error(request, "Error: Passwords must match", extra_tags="alert alert-danger")
            return render(request, "auctions/register.html")

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            messages.error(request, "Error: Username already taken", extra_tags="alert alert-danger")
            return render(request, "auctions/register.html")
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url="/login")
def user(request):
    return render(request, "auctions/user.html")

def categories(request):
    # Retrieves category list and counts entries for each
    categories = Category.objects.all().order_by("category")
    counts = {}
    for category in categories:
        count = Listing.objects.filter(category_id=category.id, active=True).count()
        counts.update({ category.id : count })

    return render(request, "auctions/categories.html", {
        "categories": categories,
        "counts": counts
    })

@login_required(login_url="/login")
def create(request):
    if request.method == "POST":
        form = CreateListing(request.POST)

        if form.is_valid():

            # Initialises category, sets data if present
            category = None
            if form.cleaned_data["category"]:
                category = form.cleaned_data["category"]
            
            listing = Listing.objects.create(
                title=form.cleaned_data["title"], 
                owner_id=form.cleaned_data["owner"], 
                description=form.cleaned_data["description"], 
                starting_bid=form.cleaned_data["starting_bid"], 
                image_URL=form.cleaned_data["image_URL"], 
                category_id=category)

            return HttpResponseRedirect(reverse("auctions:listing", args=[listing.id]))
        else:
            messages.error(request, "Error: Invalid submission", extra_tags="alert alert-danger")
            return render(request, "auctions/create.html", {
                "form": form,
            })
    else:
        form = CreateListing(initial={"owner": request.user.id})
        return render(request, "auctions/create.html", {
            "form": form
        })

@login_required(login_url="/login")
def watchlist(request):
    user = request.user.id

    if request.method == "POST":

        # Gets or creates watchlist entry for listing/user combo 
        obj, created = Watchlist.objects.get_or_create(
            listing_id = request.POST["watchlist"],
            user_id = user
        )

        # message = "Added to watchlist"

        # If entry exists - deletes
        if created == False:
            Watchlist.objects.filter(id=obj.id).delete()
            # message = "Removed from watchlist"

        return HttpResponseRedirect(reverse("auctions:listing", args=[request.POST["watchlist"]]))

    else:
        user_object = User.objects.filter(id=user).get()
        watchlist = user_object.watchlist.all()

        # Retrieve bids
        bids = {}
        for entry in watchlist:
            bids.update(get_bid(entry.listing))
        
        return render(request, "auctions/watchlist.html", {
            "watchlist": watchlist,
            "bids": bids
        })

def listing(request, listing_id):

    # Initialises variables and forms for use in all routes
    # Initialised in order of requirement
    user = request.user.id
    listing = Listing.objects.filter(id=listing_id).first()
    if listing == None:
        messages.error(request, "Error: Listing does not exist", extra_tags="alert alert-danger")
        return HttpResponseRedirect(reverse("auctions:index"))
    bid_item = Bid.objects.filter(listing=listing.id).order_by('-bid_amount').first()
    if bid_item == None:
        bid = listing.starting_bid
    else:
        bid = bid_item.bid_amount
    watchlist = Watchlist.objects.filter(user_id=user, listing_id=listing).exists()
    comments = Comment.objects.filter(listing_id=listing.id)
    form_bid = BidForm(initial={"current_bid": bid, "listing_id": listing.id, "user_id": user})
    form_comment = CommentForm(initial={"listing_id": listing.id, "user_id": user})

    if request.method == "POST":

        # New bid path
        if "submit_bid" in request.POST:
            form = BidForm(request.POST)

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    <ul>
        <form action="{% url 'auctions:index' %}" method="post">
            {% for category in categories %}
                {% csrf_token %}
                <li>
                    <button class="btn btn-link" type="submit" value="{{ category.id }}" name="category">
                        {{ category.category }}
                        {% for key, value in counts.items %}
                            {% if key == category.id %}
                                ({{ value }})
                            {% endif %}
                        {% endfor %}
                    </button>
                </li>
            {% endfor %}
        </form>
    </ul>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Listing</h2>
    <form class="form-listing" action="{% url 'auctions:create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.id_for_label != 'id_owner' %}
                    <h5>{{ field.label_tag }}</h5>
                {% endif %}
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Create Listing</button>
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>
        Active Listings
        {% if category %}
            - <small class="text-muted">{{ category }}</small>
        {% endif %}
    </h2>

    <ul class="list-group">
        {% for listing in listings %}
            <li class="list-group-item"> 
                <div>
                    <a href="{% url 'auctions:listing' listing.id %}" >{{ listing.title }} </a>
                    
                    {% for key, value in bids.items %}
                        {% if key == listing.id %}
                            {% if value %}
                                £{{ value.bid_amount }}
                            {% else %}
                                £{{ listing.starting_bid }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
                {% if listing.image_URL %}
                    <img class="img-thumbnail" src={{ listing.image_URL}}>
                {% else %}
                    <img class="img-thumbnail" src="/static/auctions/noimage.png">
                {% endif %}
                <div>{{ listing.description }}</div>
            </li>
        {% empty %}
            <li>No results found</li>
        {% endfor %}
    </ul>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
                <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist'%}">Watchlist</a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:user' %}">User</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <ul class="nav">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <form action="{% url 'auctions:watchlist' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" value="{{ listing.id }}" name="watchlist" 
                        {% if watchlist == True %}
                            class="btn btn-light watchlist watchlist-selected"
                        {% else %} 
                            class="btn btn-light watchlist watchlist-unselected"
                        {% endif %}
                    > Watchlist
                    </button>
                </form> 
            </li>
        {% endif %}
        <li class="nav-item"> <h2>{{ listing.title }}</h2> </li>
    </ul>
    <div>
        {% if listing.image_URL %}
            <img src={{ listing.image_URL }}>
        {% else %}
            <img src="/static/auctions/noimage.png">
        {% endif %}
        <p>{{ listing.description }}</p>
    </div>
    {% if user.id == listing.owner_id and listing.active %}
        <div class="form-group">
            <form action="{% url 'auctions:listing' listing.id %}" method="post">
                {% csrf_token %}
                <button class="form-group-item btn btn-danger" type="submit" value="{{ listing.id }}" name="close">
                    Close Listing
                </button>
            </form>
        </div>
    {% endif %}

    <h4>Bids</h4>

    {% if listing.active %}
        <p>Current bid: £{{ bid }}</p>
    {% else %}
        {% if user.id == bid_item.user_id %}
            <p>Congratulations! You won the auction on this item with a bid of £{{ bid }}</p>
        {% else %}
            <p> The auction has now ended and the item has been sold. </p>
        {% endif %}
    {% endif %}
    {% if user.is_authenticated and user.id != listing.owner_id and listing.active %}
        {% if user.id != bid_item.user_id %}
            <form action="{% url 'auctions:listing' listing.id %}" method="post">
                {% csrf_token %}
                {{ form_bid.non_field_errors }}
                {% for field in form_bid %}
                    {% if field.id_for_label == "id_bid_amount" %}
                        <h6>{{ field.label_tag }}</h6>
                    {% endif %}
                    <div class="form-group">
                        {{ field }}
                        {% if field.help_text %}
                            <p class="form-group-item help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div> 
                    {{ field.errors }}
                {% endfor %}
                <button type="submit" class="btn btn-primary" name="submit_bid">Submit bid</button>
            </form>
        {% else %}
            <p>Your bid is currently winning!</p>
        {% endif %}
    {% endif %}



    <h4>Comments</h4>
    <ul class="list-group comments">
        {% for comment in comments %}
            <li class="list-group-item">
                {{ comment.comment }}
            </li>
        {% empty %}
            <p>No comments, be the first to say something!</p>
        {% endfor %}
    </ul>

    {% if user.is_authenticated and listing.active %}
        <form action="{% url 'auctions:listing' listing.id %}" method="post">
            {% csrf_token %}
            {{ form_comment.non_field_errors }}
            {% for field in form_comment %}
                {% if field.id_for_label == "id_comment" %}
                    <h6>{{ field.label_tag }}</h6>
                {% endif %}
                <div class="form-group">
                    {{ field }}
                    {% if field.help_text %}
                        <p class="form-group-item help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div> 
                {{ field.errors }}
            {% endfor %}
            <button type="submit" class="btn btn-primary" name="submit_comment">Comment</button>
        </form>
    {% endif %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/user.html
{% extends "auctions/layout.html" %}

{% block body %}
    TO DO
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Watchlist</h2>
    <ul class="list-group">
        {% for entry in watchlist %}
            <li class="list-group-item"> 
                <div>
                    <a href="{% url 'auctions:listing' entry.listing.id %}"> {{ entry.listing.title }} </a>
                    {% for key, value in bids.items %}
                        {% if key == entry.listing.id %}
                            {% if value %}
                                £{{ value.bid_amount }}
                            {% else %}
                                £{{ entry.listing.starting_bid }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div>
                    {% if entry.listing.image_URL %}
                        <img class="img-thumbnail" src={{ entry.listing.image_URL }}>
                    {% else %}
                        <img class="img-thumbnail" src="/static/auctions/noimage.png">
                    {% endif %}
                </div>
                <div>
                    {{ entry.listing.description }}
                </div>
            </li>
            {% empty %}
                <li>No items in watchlist</li>
        {% endfor %}
    </ul>
{% endblock %}